### ISSUE TITLE
maven source compilation issue

### ISSUE THREAD

**Issue by ymnliu** [OHNLP/UIMA-Stream-Server#1]
Need to add the properties below in the `pom.xml` of `UIMA-Server-REST`.

```
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
```

**Comment by qqndrew** [comment]
You need to specify a maven profile - namely you want to run mvn -P EXECUTABLE clean install for the executable version or mvn -P API for a dependency version

Reason for this is because one is for shaded executable jar file with spring boot, other is for api without shading all the dependencies in.

Will update documentation to reflect this.
